# Generated by Django 6.0.4 on 2026-04-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('client_type', models.CharField(choices=[('retail', 'Retail'), ('institutional', 'Institutional')], max_length=20)),
                ('risk_tolerance', models.CharField(max_length=50)),
                ('investment_goal', models.CharField(max_length=100)),
                ('time_horizon', models.IntegerField()),
            ],
        ),
    ]
