# Generated by Django 6.0.4 on 2026-04-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_type', models.CharField(choices=[('mutual funds', 'Mutual Funds'), ('closed-end funds', 'Closed-end Funds'), ('investment trust', 'Investment Trust')], max_length=20)),
                ('assets_held', models.PositiveBigIntegerField()),
                ('target_return', models.PositiveSmallIntegerField(default=0, max_length=3)),
                ('return_objective', models.CharField(choices=[('capital ', 'Capital Growth'), ('income ', 'Income Generation'), ('total ', 'Total Return')], max_length=20)),
                ('benchmark', models.CharField(choices=[('s&p 500', 'S&P 500'), ('bond index', 'Bond index'), ('multi-asset', 'Multi-asset benchmark'), ('custom', 'Custom')], max_length=20)),
                ('performance', models.CharField(choices=[('match', 'Match benchmark'), ('outperforn', 'Outperform'), ('minimize', 'Minimize downside vs benchmark')], max_length=20)),
                ('risk_tolerance', models.CharField(choices=[('conservative', 'Conservative'), ('aggressive', 'Aggressive'), ('moderate', 'Moderate')], max_length=20)),
                ('liquidity', models.CharField(choices=[('high', 'Daily'), ('medium', 'Monthly'), ('low', 'long-term')], max_length=20)),
                ('manager_numbers', models.PositiveIntegerField(max_length=3)),
                ('time_horizon', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RetailClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('client_goals', models.CharField(choices=[('retirement', 'Retirement Planning'), ('independence', 'Financial Independence'), ('preservation', 'Wealth Preservation')], max_length=20)),
                ('age', models.PositiveIntegerField(max_length=3)),
                ('risk_tolerance', models.CharField(max_length=50)),
                ('investment_goal', models.CharField(max_length=100)),
                ('time_horizon', models.IntegerField()),
                ('identity_number', models.PositiveBigIntegerField(max_length=13)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
