# Generated by Django 6.0.4 on 2026-04-15 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_institutionalclient_retailclient_delete_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailclient',
            name='risk_tolerance',
            field=models.CharField(choices=[('conservative', 'Conservative'), ('aggressive', 'Aggressive'), ('moderate', 'Moderate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='retailclient',
            name='time_horizon',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institutional_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.institutionalclient')),
                ('retail_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.retailclient')),
            ],
        ),
        migrations.CreateModel(
            name='AssetManaged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('allocation_percentage', models.FloatField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.portfolio')),
            ],
        ),
    ]
