# Generated by Django 6.0.4 on 2026-04-15 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_retailclient_risk_tolerance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='institutional_client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.institutionalclient'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='retail_client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.retailclient'),
        ),
    ]
