# Generated by Django 6.0.4 on 2026-04-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_portfolio_institutional_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='total_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
