# Generated by Django 6.0.4 on 2026-04-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_portfolio_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='total_value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
