# Generated by Django 6.0.4 on 2026-04-15 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_institutionalclient_user_retailclient_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionalclient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='retailclient',
            name='user',
        ),
    ]
