# Generated by Django 6.0.4 on 2026-04-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_remove_institutionalclient_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailclient',
            name='risk_tolerance',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], max_length=20),
        ),
    ]
