# Generated by Django 6.0.4 on 2026-04-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_retailclient_risk_tolerance'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionalclient',
            name='organization_name',
            field=models.CharField(default='org', max_length=100),
        ),
        migrations.AlterField(
            model_name='retailclient',
            name='name',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
