# Generated by Django 6.0.4 on 2026-04-16 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_remove_institutionalclient_benchmark_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailclient',
            name='email',
        ),
        migrations.AddField(
            model_name='institutionalclient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='institutionalclient',
            name='manager_numbers',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='institutionalclient',
            name='target_return',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutional_client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.institutionalclient')),
                ('retail_client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.retailclient')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
