# Generated by Django 6.0.4 on 2026-04-23 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_retailclient_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='institutional_client',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='institutional_client',
        ),
        migrations.RemoveField(
            model_name='retailclient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='retail_client',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='retail_client',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='user', max_length=100)),
                ('risk_rating', models.CharField(choices=[('low', 'Low'), ('pure equity', 'Pure Equity'), ('low-medium', 'Low-Medium'), ('medium', 'Medium'), ('high', 'High'), ('flexible', 'Flexible')])),
                ('age', models.PositiveIntegerField(default=18)),
                ('risk_tolerance', models.CharField(choices=[('money maket', 'Money Market'), ('sa ma income', '(ASISA) South African MA Income'), ('sa ma low equity', '(ASISA) South African MA Low Equity'), ('sa ma medium equity', '(ASISA) South African MA Medium Equity'), ('sa ma high equity', '(ASISA) South African MA High Equity'), ('ww ma flexible', '(ASISA) Worldwide MA Flexible'), ('sa equity', 'SA Equity'), ('usd cash', 'USD Cash'), ('eaa fund usd cautious', 'EAA Fund USD Cautious Allocation'), ('eaa fund usd moderate', 'EAA Fund USD Moderate Allocation'), ('eaa fund usd aggressive', 'EAA Fund USD Aggressive Allocation'), ('international equity', 'International Equity (ZAR)')])),
                ('investment_goal', models.CharField(default='None', max_length=100)),
                ('time_horizon', models.PositiveBigIntegerField()),
                ('risk_profile', models.CharField(default=[('conservative', 'Conservative'), ('aggressive', 'Aggressive'), ('moderate', 'Moderate'), ('mod-aggressive', 'Moderate Aggressive')])),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AddField(
            model_name='profile',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.DeleteModel(
            name='InstitutionalClient',
        ),
        migrations.DeleteModel(
            name='RetailClient',
        ),
    ]
