# Generated by Django 6.0.4 on 2026-04-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_remove_profile_institutional_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='risk_profile',
            field=models.CharField(choices=[('conservative', 'Conservative'), ('aggressive', 'Aggressive'), ('moderate', 'Moderate'), ('mod-aggressive', 'Moderate Aggressive')]),
        ),
    ]
