# Generated by Django 6.0.4 on 2026-04-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_alter_client_risk_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_group',
            field=models.CharField(choices=[('acs', 'ACS'), ('bk wealth', 'BK Wealth'), ('clamart wealth', 'Clamart Wealth'), ('delta', 'Delta'), ('graviton', 'Graviton'), ('Fiducia wealth (pty) ltd', 'Fiducia Wealth (Pty) Ltd'), ('fiscal tree', 'Fiscal Tree'), ('absolute absolut funds', 'Graviton Absolute Funds'), ('graviton global funds', 'Graviton Global Funds'), ('graviton hedge funds', 'Graviton Hedge Funds'), ('graviton hybrid funds', 'Graviton Hybrid Funds'), ('graviton offshore funds (franchise)', 'Graviton Offshore Funds (Franchise)'), ('graviton retirement solutions', 'Graviton Retirement Solutions'), ('graviton sharia funds', 'Graviton Sharia Funds'), ('graviton wealth', 'Graviton Wealth'), ('graviton wealth (franchise)', 'Graviton Wealth (Franchise)'), ('guardian', 'Guardian'), ('henceforward', 'Henceforward'), ('innovate solutions group (pty) ltd', 'Innovate Solutions Group (Pty) Ltd'), ('jurien jordaan', 'Jurien Jordaan'), ('Justin frittelli', 'Justin Frittelli'), ('latitude wealth', 'Latitude Wealth'), ('luthuli capital', 'Luthuli Capital'), ('lw funds', 'LW Funds'), ('lynnwood financial services (pty) ltd', 'Lynnwood Financial Services (Pty) Ltd'), ('nld', 'NLD'), ('optimate', 'Optimate'), ('psg wealth bryanston', 'PSG Wealth Bryanston'), ('rebalance', 'Rebalance'), ('sanlam multi manager international', 'Sanlam Multi Manager International'), ('victory house', 'Victory House'), ('wealth design', 'Wealth Design'), ('zingitwa wealth', 'Zingitwa Wealth'), ('other', 'Other')], default='other'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='client_group',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_name',
            field=models.CharField(default='portfolio', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='risk_profile',
            field=models.CharField(choices=[('conservative', 'Conservative'), ('aggressive', 'Aggressive'), ('moderate', 'Moderate'), ('mod-aggressive', 'Moderate Aggressive'), ('global-moderate', 'Global Moderate'), ('global-aggressive', 'Global Aggressive'), ('global-cautious', 'Global Cautious')]),
        ),
    ]
