# Generated by Django 6.0.4 on 2026-04-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_client_client_group_portfolio_client_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='fund_category',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='risk_profile',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
