# Generated by Django 6.0.4 on 2026-04-24 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_portfolio_fund_category_portfolio_risk_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_name',
        ),
    ]
