# Generated by Django 6.0.4 on 2026-04-28 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_alter_client_client_group_alter_client_risk_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_group',
            field=models.CharField(blank=True, choices=[('ACS', 'ACS'), ('BKA Wealth', 'BKA Wealth'), ('Clamart Wealth', 'Clamart Wealth'), ('Delta', 'Delta'), ('Fiducia Wealth (Pty) Ltd', 'Fiducia Wealth (Pty) Ltd'), ('Fiscal Tree', 'Fiscal Tree'), ('Graviton', 'Graviton'), ('Graviton Absolute Funds', 'Graviton Absolute Funds'), ('Graviton Global Funds', 'Graviton Global Funds'), ('Graviton Hedge Funds', 'Graviton Hedge Funds'), ('Graviton Hybrid Funds', 'Graviton Hybrid Funds'), ('Graviton Offshore (Franchises)', 'Graviton Offshore (Franchises)'), ('Graviton Retirement Solution', 'Graviton Retirement Solution'), ('Graviton Shariah Funds', 'Graviton Shariah Funds'), ('Graviton Wealth', 'Graviton Wealth'), ('Graviton Wealth (Franchises)', 'Graviton Wealth (Franchises)'), ('Graviton Wealth Management', 'Graviton Wealth Management'), ('Guardian', 'Guardian'), ('Henceforward', 'Henceforward'), ('Innovate Solutions Group (Pty) Ltd', 'Innovate Solutions Group (Pty) Ltd'), ('Jurien Jordaan', 'Jurien Jordaan'), ('Justin Frittelli', 'Justin Frittelli'), ('LW Funds', 'LW Funds'), ('Latitude Wealth', 'Latitude Wealth'), ('Luthuli Capital', 'Luthuli Capital'), ('Lynnwood Financial Services (Pty) Ltd', 'Lynnwood Financial Services (Pty) Ltd'), ('NLD', 'NLD'), ('Optimate', 'Optimate'), ('PSG Wealth Bryanston', 'PSG Wealth Bryanston'), ('Rebalance', 'Rebalance'), ('Sanlam Multi Manager International', 'Sanlam Multi Manager International'), ('Victory House', 'Victory House'), ('Wealth Design', 'Wealth Design'), ('Zingitwa Wealth', 'Zingitwa Wealth'), ('Other', 'Other')], default='other'),
        ),
        migrations.AlterField(
            model_name='client',
            name='risk_profile',
            field=models.CharField(blank=True, choices=[('Conservative', 'Conservative'), ('Aggressive', 'Aggressive'), ('Moderate', 'Moderate'), ('Moderate Aggressive', 'Moderate Aggressive'), ('Global Moderate', 'Global Moderate'), ('Global Moderate Aggressive', 'Global Moderate Aggressive'), ('Global Aggressive', 'Global Aggressive'), ('Global Cautious', 'Global Cautious'), ('Global Conservative', 'Global Conservative'), ('Cautious', 'Cautious')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='risk_rating',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('pure equity', 'Pure Equity'), ('low-medium', 'Low-Medium'), ('medium', 'Medium'), ('high', 'High'), ('flexible', 'Flexible')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='risk_tolerance',
            field=models.CharField(blank=True, choices=[('(ASISA) South African MA Income', '(ASISA) South African MA Income'), ('(ASISA) South African MA Low Equity', '(ASISA) South African MA Low Equity'), ('(ASISA) South African MA Medium Equity', '(ASISA) South African MA Medium Equity'), ('(ASISA) South African MA High Equity', '(ASISA) South African MA High Equity'), ('(ASISA) Wwide MA Flexible', '(ASISA) Wwide MA Flexible'), ('EAA Fund USD Cautious Allocation', 'EAA Fund USD Cautious Allocation'), ('EAA Fund USD Moderate Allocation', 'EAA Fund USD Moderate Allocation'), ('EAA Fund USD Aggressive Allocation', 'EAA Fund USD Aggressive Allocation'), ('EAA Fund USD Diversified Bond - Short Term', 'EAA Fund USD Diversified Bond - Short Term'), ('SA Equity', 'SA Equity')]),
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_group', models.CharField(choices=[('ACS', 'ACS'), ('BKA Wealth', 'BKA Wealth'), ('Clamart Wealth', 'Clamart Wealth'), ('Delta', 'Delta'), ('Fiducia Wealth (Pty) Ltd', 'Fiducia Wealth (Pty) Ltd'), ('Fiscal Tree', 'Fiscal Tree'), ('Graviton', 'Graviton'), ('Graviton Absolute Funds', 'Graviton Absolute Funds'), ('Graviton Global Funds', 'Graviton Global Funds'), ('Graviton Hedge Funds', 'Graviton Hedge Funds'), ('Graviton Hybrid Funds', 'Graviton Hybrid Funds'), ('Graviton Offshore (Franchises)', 'Graviton Offshore (Franchises)'), ('Graviton Retirement Solution', 'Graviton Retirement Solution'), ('Graviton Shariah Funds', 'Graviton Shariah Funds'), ('Graviton Wealth', 'Graviton Wealth'), ('Graviton Wealth (Franchises)', 'Graviton Wealth (Franchises)'), ('Graviton Wealth Management', 'Graviton Wealth Management'), ('Guardian', 'Guardian'), ('Henceforward', 'Henceforward'), ('Innovate Solutions Group (Pty) Ltd', 'Innovate Solutions Group (Pty) Ltd'), ('Jurien Jordaan', 'Jurien Jordaan'), ('Justin Frittelli', 'Justin Frittelli'), ('LW Funds', 'LW Funds'), ('Latitude Wealth', 'Latitude Wealth'), ('Luthuli Capital', 'Luthuli Capital'), ('Lynnwood Financial Services (Pty) Ltd', 'Lynnwood Financial Services (Pty) Ltd'), ('NLD', 'NLD'), ('Optimate', 'Optimate'), ('PSG Wealth Bryanston', 'PSG Wealth Bryanston'), ('Rebalance', 'Rebalance'), ('Sanlam Multi Manager International', 'Sanlam Multi Manager International'), ('Victory House', 'Victory House'), ('Wealth Design', 'Wealth Design'), ('Zingitwa Wealth', 'Zingitwa Wealth'), ('Other', 'Other')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.advisor'),
        ),
    ]
