# Generated by Django 6.0.4 on 2026-05-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_alter_client_client_group_alter_client_risk_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='journey',
            field=models.CharField(blank=True, choices=[('not started', 'NOT_STARTED'), ('on-track', 'ON-TRACK'), ('complete', 'COMLPETE')]),
        ),
        migrations.AddField(
            model_name='client',
            name='questionnaire_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Final')], default='FINAL', max_length=10),
        ),
    ]
