# Generated by Django 6.0.4 on 2026-05-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_client_journey_client_questionnaire_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='financial_goal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target rand amount the client wants to reach', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='has_liabilities',
            field=models.BooleanField(blank=True, help_text='Does the client have significant debt (home loan, credit, vehicle finance)?', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='monthly_surplus',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly income minus monthly expenses (disposable surplus)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='number_of_dependants',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of people financially dependent on the client', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='total_investable_assets',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total rand value of all investable assets', max_digits=14, null=True),
        ),
    ]
