# Generated by Django 6.0.4 on 2026-05-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_client_financial_goal_amount_client_has_liabilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='questionnaire_step',
            field=models.PositiveSmallIntegerField(default=1, help_text='Last step the advisor reached in the questionnaire (1–7)'),
        ),
    ]
