# Generated by Django 6.0.4 on 2026-05-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_client_questionnaire_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='questionnaire_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ONGOING', 'Ongoing'), ('ACTIVE', 'Active')], default='ONGOING', max_length=10),
        ),
    ]
